export const LANGUAGES = [
  { code: 'ar', name: 'Arabic', nativeName: 'العربية' },
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'es', name: 'Spanish', nativeName: 'Español' },
  { code: 'fr', name: 'French', nativeName: 'Français' },
  { code: 'de', name: 'German', nativeName: 'Deutsch' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português' },
  { code: 'zh', name: 'Chinese', nativeName: '中文' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語' },
  { code: 'ko', name: 'Korean', nativeName: '한국어' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский' },
];

// Comprehensive translations for the app
export const translations = {
  Arabic: {
    // Settings
    settings: 'الإعدادات',
    appSettings: 'إعدادات التطبيق',
    appearance: 'المظهر',
    darkMode: 'الوضع المظلم',
    language: 'اللغة',
    units: 'الوحدات',
    audioHaptics: 'الصوت واللمس',
    soundEffects: 'المؤثرات الصوتية',
    hapticFeedback: 'ردود الفعل اللمسية',
    dataSync: 'البيانات والمزامنة',
    autoSync: 'المزامنة التلقائية',
    offlineMode: 'وضع عدم الاتصال',
    highQualityImages: 'صور عالية الجودة',
    backgroundRefresh: 'التحديث في الخلفية',
    advanced: 'متقدم',
    betaFeatures: 'ميزات تجريبية',
    clearCache: 'مسح التخزين المؤقت',
    resetSettings: 'إعادة تعيين الإعدادات',
    appInformation: 'معلومات التطبيق',
    version: 'الإصدار',
    build: 'البناء',
    lastUpdated: 'آخر تحديث',
    
    // Common
    home: 'الرئيسية',
    profile: 'الملف الشخصي',
    health: 'الصحة',
    fitness: 'اللياقة البدنية',
    wellness: 'العافية',
    aiChat: 'محادثة الذكي',
    back: 'رجوع',
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    add: 'إضافة',
    view: 'عرض',
    start: 'بدء',
    complete: 'إكمال',
    next: 'التالي',
    previous: 'السابق',
    loading: 'جاري التحميل',
    error: 'خطأ',
    success: 'نجح',
    user: 'المستخدم',
    
    // Home Screen
    goodMorning: 'صباح الخير',
    goodAfternoon: 'مساء الخير',
    goodEvening: 'مساء الخير',
    todaysOverview: 'نظرة عامة على اليوم',
    activityRings: 'حلقات النشاط',
    closeYourRings: 'أغلق حلقاتك اليوم',
    activeGoals: 'الأهداف النشطة',
    noActiveGoals: 'لا توجد أهداف نشطة',
    setFirstGoal: 'حدد هدفك الأول لبدء رحلة العافية',
    createGoal: 'إنشاء هدف',
    quickActions: 'إجراءات سريعة',
    healthCheck: 'فحص صحي',
    logVitals: 'تسجيل العلامات الحيوية',
    startWorkout: 'بدء التمرين',
    getMoving: 'ابدأ الحركة',
    mindfulness: 'اليقظة الذهنية',
    findPeace: 'اعثر على السلام',
    aiCoach: 'المدرب الذكي',
    getAdvice: 'احصل على نصيحة',
    upcoming: 'القادم',
    viewCalendar: 'عرض التقويم',
    doctorAppointment: 'موعد الطبيب',
    workoutSession: 'جلسة تمرين',
    viewDetails: 'عرض التفاصيل',
    manage: 'إدارة',
    seeAll: 'عرض الكل',
    sunny: 'مشمس',
    temperature: 'درجة الحرارة',
    annualCheckup: 'الفحص السنوي',
    tomorrow: 'غداً',
    
    // Profile Screen
    yourWellnessJourney: 'رحلة العافية الخاصة بك',
    healthOverview: 'نظرة عامة على الصحة',
    avgHeartRate: 'متوسط معدل ضربات القلب',
    dailySteps: 'الخطوات اليومية',
    moodToday: 'المزاج اليوم',
    achievements: 'الإنجازات',
    goalsProgress: 'تقدم الأهداف',
    overallProgress: 'التقدم العام',
    goalsCompleted: 'أهداف مكتملة',
    noActiveGoalsProfile: 'لا توجد أهداف نشطة',
    setFirstGoalProfile: 'حدد هدفك الأول لبدء تتبع تقدمك',
    profileSettings: 'إعدادات الملف الشخصي',
    editProfile: 'تعديل الملف الشخصي',
    updatePersonalInfo: 'تحديث معلوماتك الشخصية',
    healthPassport: 'جواز الصحة',
    viewHealthSummary: 'عرض ملخص صحتك',
    viewWellnessMilestones: 'عرض معالم العافية الخاصة بك',
    appSettingsDesc: 'الإشعارات والخصوصية والمزيد',
    recentAchievements: 'الإنجازات الأخيرة',
    viewAll: 'عرض الكل',
    goalAchiever: 'محقق الأهداف',
    completedFirstGoal: 'أكملت هدف العافية الأول!',
    consistencyMaster: 'سيد الثبات',
    sevenDayStreak: 'حافظت على سلسلة 7 أيام من التسجيلات اليومية',
    totalGoals: 'إجمالي الأهداف',
    completed: 'مكتمل',
    progress: 'التقدم',
    verified: 'موثق',
    premium: 'مميز',
    addGoal: 'إضافة هدف',
    
    // Health Screen
    yourWellnessDashboard: 'لوحة تحكم العافية الخاصة بك',
    healthStatus: 'الحالة الصحية',
    allSystemsGood: 'جميع الأنظمة تبدو جيدة',
    healthScore: 'نقاط الصحة',
    riskFactors: 'عوامل الخطر',
    trackedMetrics: 'المقاييس المتتبعة',
    symptomChecker: 'فاحص الأعراض',
    aiAssessment: 'تقييم ذكي',
    virtualConsult: 'استشارة افتراضية',
    talkToDoctor: 'تحدث مع الطبيب',
    aiNavigator: 'الملاح الذكي',
    healthGuidance: 'إرشادات صحية',
    vitalSigns: 'العلامات الحيوية',
    addReading: 'إضافة قراءة',
    heartRate: 'معدل ضربات القلب',
    bloodPressure: 'ضغط الدم',
    weight: 'الوزن',
    sleepQuality: 'جودة النوم',
    upcomingAppointments: 'المواعيد القادمة',
    noUpcomingAppointments: 'لا توجد مواعيد قادمة',
    scheduleHealthCheckup: 'حدد موعد فحصك الصحي التالي أو الاستشارة',
    scheduleAppointment: 'حجز موعد',
    medications: 'الأدوية',
    noActiveMedications: 'لا توجد أدوية نشطة',
    addMedicationsTrack: 'أضف أدويتك لتتبع الجرعات والجداول',
    addMedication: 'إضافة دواء',
    healthInsights: 'رؤى صحية',
    greatProgress: 'تقدم رائع!',
    heartRateHealthy: 'كان معدل ضربات قلبك ثابتاً في النطاق الصحي هذا الأسبوع. استمر في العمل الجيد مع تمارين القلب!',
    sleepOptimization: 'تحسين النوم',
    trackSleepQuality: 'فكر في تتبع جودة نومك لفهم أنماط طاقتك وصحتك العامة بشكل أفضل.',
    quickActionsHealth: 'إجراءات سريعة',
    
    // Fitness Screen
    stayStrongHealthy: 'ابق قوياً وصحياً',
    caloriesBurned: 'السعرات المحروقة',
    activeMinutes: 'الدقائق النشطة',
    workouts: 'التمارين',
    strength: 'القوة',
    quickStart: 'بداية سريعة',
    aiTrainer: 'المدرب الذكي',
    personalizedWorkouts: 'تمارين شخصية',
    calorieScanner: 'ماسح السعرات',
    trackNutrition: 'تتبع التغذية',
    groupTraining: 'التدريب الجماعي',
    joinOthers: 'انضم للآخرين',
    assessment: 'التقييم',
    testFitness: 'اختبار اللياقة',
    todaysWorkouts: 'تمارين اليوم',
    noWorkoutsScheduled: 'لا توجد تمارين مجدولة',
    startFitnessJourney: 'ابدأ رحلة اللياقة البدنية بتمرين سريع',
    scheduleWorkout: 'جدولة تمرين',
    progressMetrics: 'مقاييس التقدم',
    featuredTrainers: 'المدربون المميزون',
    noTrainersAvailable: 'لا يوجد مدربون متاحون',
    connectProfessionalTrainers: 'تواصل مع المدربين المحترفين لتحقيق أهدافك',
    findTrainers: 'العثور على مدربين',
    insights: 'الرؤى',
    excellentProgress: 'تقدم ممتاز!',
    increasedWorkoutIntensity: 'لقد زدت من شدة التمرين بنسبة 15% هذا الأسبوع. استمر في دفع حدودك!',
    recoveryTime: 'وقت الاستشفاء',
    considerRestDays: 'فكر في إضافة المزيد من أيام الراحة بين التمارين المكثفة للاستشفاء الأمثل.',
    viewInsights: 'عرض الرؤى',
    burnedToday: 'محروقة اليوم',
    activeTime: 'وقت نشط',
    bookSession: 'حجز جلسة',
    calories: 'السعرات',
    minutes: 'الدقائق',
    thisWeek: 'هذا الأسبوع',
    
    // Wellness Screen
    mindBodySoul: 'العقل والجسد والروح',
    howAreYouFeeling: 'كيف تشعر؟',
    feelingGood: 'أشعر بخير',
    tapToLogMood: 'اضغط لتسجيل مزاجك',
    energy: 'الطاقة',
    activeHabits: 'العادات النشطة',
    checkIn: 'تسجيل الدخول',
    logMood: 'تسجيل المزاج',
    trackFeelings: 'تتبع المشاعر',
    nutritionScanner: 'ماسح التغذية',
    trackFood: 'تتبع الطعام',
    sleepTracker: 'متتبع النوم',
    monitorRest: 'مراقبة الراحة',
    breathe: 'تنفس',
    relaxMind: 'استرخ العقل',
    wellnessScores: 'نقاط العافية',
    energyLevel: 'مستوى الطاقة',
    resilience: 'المرونة',
    improving: 'يتحسن',
    declining: 'يتراجع',
    stable: 'مستقر',
    dailyCheckIn: 'التسجيل اليومي',
    readyForCheckIn: 'مستعد للتسجيل اليومي؟',
    reflectOnDay: 'خذ لحظة للتفكير في يومك وتتبع عافيتك',
    checkInComplete: 'اكتمل التسجيل!',
    completedDailyCheckIn: 'عمل رائع في إكمال تسجيلك اليومي للعافية. استمر في الزخم!',
    todaysHabits: 'عادات اليوم',
    addHabit: 'إضافة عادة',
    noActiveHabitsWellness: 'لا توجد عادات نشطة',
    buildHealthyHabits: 'بناء عادات صحية لتحسين عافيتك اليومية',
    createFirstHabit: 'إنشاء عادتك الأولى',
    dayStreak: 'سلسلة أيام',
    moodImprovement: 'تحسن المزاج',
    moodConsistentlyPositive: 'كان مزاجك إيجابياً باستمرار هذا الأسبوع. استمر في العمل الرائع مع روتين العافية!',
    energyBoost: 'دفعة طاقة',
    tryMorningMeditation: 'جرب إضافة تأمل صباحي لمدة 10 دقائق لتعزيز مستويات طاقتك طوال اليوم.',
    mindfulnessWellness: 'اليقظة الذهنية',
    
    // AI Chat Screen
    aiHealthCoach: 'مدرب الصحة الذكي',
    personalWellnessAssistant: 'مساعد العافية الشخصي',
    oneHealthAI: 'ذكي الصحة الواحد',
    onlineReady: 'متصل وجاهز',
    personalizedInsights: 'رؤى شخصية',
    aiThinking: 'الذكي يفكر...',
    askAnythingHealth: 'اسأل أي شيء عن صحتك',
    goalProgress: 'تقدم الهدف',
    motivation: 'التحفيز',
    newPlan: 'خطة جديدة',
    dailyFocus: 'التركيز اليومي',
    
    // Common Status
    normal: 'طبيعي',
    elevated: 'مرتفع',
    good: 'جيد',
    excellent: 'ممتاز',
    okay: 'مقبول',
    low: 'منخفض',
    terrible: 'سيء',
    
    // Units
    bpm: 'ن/د',
    mmHg: 'مم زئبق',
    kg: 'كغ',
    score: 'نقاط',
    kcal: 'سعرة',
    min: 'دقيقة',
    steps: 'خطوات',
    earned: 'مكتسب',
    feeling: 'شعور',
    
    // Time
    today: 'اليوم',
    yesterday: 'أمس',
    lastNight: 'الليلة الماضية',
    daysAgo: 'أيام مضت',
    weekAgo: 'أسبوع مضى',
    
    // Login & Onboarding
    signInWithPhone: 'تسجيل الدخول بالهاتف',
    sendVerificationCode: 'إرسال رمز التحقق',
    enterVerificationCode: 'أدخل رمز التحقق',
    verifyAndContinue: 'تحقق ومتابعة',
    phoneNumber: 'رقم الهاتف',
    verificationCode: 'رمز التحقق',
    resendCode: 'إعادة إرسال الرمز',
    didntReceiveCode: 'لم تستلم الرمز؟',
    letsGetToKnowYou: 'دعنا نتعرف عليك',
    personalizeHealthJourney: 'سنستخدم هذا لتخصيص رحلة صحتك',
    fullName: 'الاسم الكامل',
    enterYourName: 'أدخل اسمك',
    nationalId: 'الهوية الوطنية',
    email: 'البريد الإلكتروني',
    basicInformation: 'المعلومات الأساسية',
    accurateRecommendations: 'هذا يساعدنا في تقديم توصيات أكثر دقة',
    age: 'العمر',
    gender: 'الجنس',
    male: 'ذكر',
    female: 'أنثى',
    other: 'آخر',
    preferNotToSay: 'أفضل عدم القول',
    bodyMeasurements: 'قياسات الجسم',
    calculateFitnessNeeds: 'سنستخدم هذا لحساب احتياجات اللياقة البدنية',
    height: 'الطول',
    enterYourHeight: 'أدخل طولك',
    enterYourWeight: 'أدخل وزنك',
    uploadMedicalReports: 'رفع التقارير الطبية',
    whatAreYourGoals: 'ما هي أهدافك؟',
    selectAllThatApply: 'اختر كل ما ينطبق عليك',
    loseWeight: 'فقدان الوزن',
    buildMuscle: 'بناء العضلات',
    improveFitness: 'تحسين اللياقة',
    increaseStrength: 'زيادة القوة',
    improveFlex: 'تحسين المرونة',
    reduceStress: 'تقليل التوتر',
    betterSleepOnboarding: 'نوم أفضل',
    moreEnergy: 'طاقة أكثر',
    medicalHistory: 'التاريخ الطبي',
    understandHealthBackground: 'ساعدنا في فهم خلفيتك الصحية',
    anyConditions: 'هل لديك أي من هذه الحالات؟',
    fitnessLevel: 'مستوى اللياقة',
    rightWorkoutPlan: 'هذا يساعدنا في إنشاء خطة التمرين المناسبة',
    beginner: 'مبتدئ',
    intermediate: 'متوسط',
    advanced: 'متقدم',
    newToExercise: 'جديد في التمرين أو العودة بعد انقطاع',
    exerciseRegularly: 'أتمرن 2-3 مرات في الأسبوع بانتظام',
    exerciseConsistently: 'أتمرن 4+ مرات في الأسبوع باستمرار',
    lifestyleInformation: 'معلومات نمط الحياة',
    dailyHabits: 'أخبرنا عن عاداتك اليومية',
    averageSleepHours: 'متوسط ساعات النوم في الليلة',
    currentStressLevel: 'مستوى التوتر الحالي (1-10)',
    dietaryPreferences: 'التفضيلات الغذائية',
    occupation: 'المهنة',
    behavioralPreferences: 'التفضيلات السلوكية',
    howMotivated: 'ساعدنا في فهم كيف تحب أن تكون محفزاً',
    whatMotivatesYou: 'ما الذي يحفزك أكثر؟',
    competitionChallenges: 'المنافسة والتحديات',
    teamCommunity: 'الفريق والمجتمع',
    personalAchievementMotivation: 'الإنجاز الشخصي',
    gentleSupport: 'الدعم اللطيف',
    preferredWorkoutTime: 'وقت التمرين المفضل',
    morning: 'الصباح',
    afternoon: 'بعد الظهر',
    evening: 'المساء',
    flexible: 'مرن',
    reminderStyle: 'نمط التذكير',
    gentle: 'لطيف',
    firm: 'حازم',
    motivational: 'تحفيزي',
    goalPersonalization: 'تخصيص الأهداف',
    customizeGoalSetting: 'دعنا نخصص تجربة وضع الأهداف',
    primaryFocus: 'ما هو تركيزك الأساسي؟',
    balancedFocus: 'متوازن',
    whatMotivatesYouSelect: 'ما الذي يحفزك؟ (اختر كل ما ينطبق)',
    healthImprovement: 'تحسين الصحة',
    weightManagement: 'إدارة الوزن',
    stressRelief: 'تخفيف التوتر',
    betterSleepGoal: 'نوم أفضل',
    increasedEnergy: 'طاقة متزايدة',
    socialConnection: 'التواصل الاجتماعي',
    personalAchievementGoal: 'الإنجاز الشخصي',
    diseasePrevention: 'الوقاية من الأمراض',
    preferredGoalTimeframe: 'الإطار الزمني المفضل للهدف',
    shortTerm: 'قصير (1-3 أشهر)',
    mediumTerm: 'متوسط (3-6 أشهر)',
    longTerm: 'طويل (6+ أشهر)',
    trackingDetail: 'كم من التفاصيل تريد في التتبع؟',
    detailed: 'مفصل',
    simple: 'بسيط',
    minimal: 'أدنى حد',
    specificGoals: 'أهداف محددة',
    personalizedGoalsSetup: 'دعنا نضع أهدافك الشخصية',
    weightGoal: 'هدف الوزن',
    loseWeightGoal: 'فقدان الوزن',
    gainWeight: 'زيادة الوزن',
    maintainWeight: 'الحفاظ على الوزن',
    reduceBodyWeight: 'تقليل وزن الجسم',
    increaseBodyWeight: 'زيادة وزن الجسم',
    keepCurrentWeight: 'الحفاظ على الوزن الحالي',
    targetWeight: 'الوزن المستهدف',
    timeframeMonths: 'الإطار الزمني (أشهر)',
    energyGoal: 'هدف الطاقة',
    increaseEnergyGoal: 'زيادة الطاقة',
    stabilizeEnergy: 'استقرار الطاقة',
    betterMorningEnergy: 'طاقة صباحية أفضل',
    feelMoreEnergetic: 'الشعور بطاقة أكثر طوال اليوم',
    avoidEnergyCrashes: 'تجنب انهيار الطاقة والحفاظ على مستويات ثابتة',
    wakeUpRefreshed: 'الاستيقاظ بشعور منتعش',
    targetEnergyLevel: 'مستوى الطاقة المستهدف (1-10)',
    stressReductionGoal: 'هدف تقليل التوتر',
    targetStressLevel: 'مستوى التوتر المستهدف (1-10، أقل أفضل)',
    continueBtn: 'متابعة',
    completeSetup: 'إكمال الإعداد',
    
    // Additional common terms
    camera: 'الكاميرا',
    gallery: 'المعرض',
    optional: 'اختياري',
    sending: 'جاري الإرسال',
    verifying: 'جاري التحقق',
    encrypted: 'مشفر',
    neverShared: 'لا يتم مشاركته أبداً',
    thirdParties: 'أطراف ثالثة',
    phoneEncrypted: 'رقم هاتفك مشفر ولا يتم مشاركته مع أطراف ثالثة',
    sendingCode: 'جاري إرسال الرمز...',
    verifyingCode: 'جاري التحقق...',
    sentCodeTo: 'أرسلنا رمز مكون من 4 أرقام إلى',
    
    // Additional UI elements
    distance: 'المسافة',
    km: 'كم',
    activeTimeShort: 'وقت نشط',
    
    // Additional wellness terms
    meditation: 'التأمل',
    morningCalm: 'هدوء الصباح',
    stressReliefMeditation: 'تخفيف التوتر',
    sleepStories: 'قصص النوم',
    
    // Additional fitness terms
    pushUps: 'تمارين الضغط',
    squats: 'القرفصاء',
    customWorkout: 'تمرين مخصص',
    
    // Additional health terms
    provider: 'المقدم',
    appointment: 'الموعد',
    dosage: 'الجرعة',
    frequency: 'التكرار',
    
    // Additional profile terms
    completedGoals: 'الأهداف المكتملة',
    progressPercentage: 'نسبة التقدم',
    
    // Additional onboarding terms
    chronicConditions: 'الحالات المزمنة',
    fitnessLimitations: 'قيود اللياقة البدنية',
    ehrSystem: 'نظام السجلات الصحية الإلكترونية',
    connectEHR: 'ربط السجلات الصحية',
    ehrConnected: 'تم ربط السجلات الصحية',
    primaryCareProvider: 'مقدم الرعاية الأولية',
    lastPhysicalExam: 'آخر فحص طبي',
    
    // Status messages
    planCreated: 'تم إنشاء الخطة!',
    personalizedPlanCreated: 'تم إنشاء خطتك الشخصية وإضافتها إلى ملفك الشخصي. يمكنك تتبع تقدمك في قسم الصحة.',
    failedToCreatePlan: 'فشل في إنشاء الخطة. يرجى المحاولة مرة أخرى.',
    
    // Additional common terms
    of: 'من',
    at: 'في',
    on: 'في',
    and: 'و',
    or: 'أو',
    with: 'مع',
    without: 'بدون',
    for: 'لـ',
    from: 'من',
    to: 'إلى',
    in: 'في',
    
    // Sleep related
    sleep: 'النوم',
    sleepHours: 'ساعات النوم',
    sleepQualityScore: 'نقاط جودة النوم',
    
    // Mood related
    mood: 'المزاج',
    moodScore: 'نقاط المزاج',
    moodTracking: 'تتبع المزاج',
    
    // Exercise related
    exercise: 'التمرين',
    exercises: 'التمارين',
    workout: 'التمرين',
    workoutPlan: 'خطة التمرين',
    
    // Nutrition related
    nutrition: 'التغذية',
    nutritionPlan: 'خطة التغذية',
    
    // Medical related
    medical: 'طبي',
    medicalRecord: 'السجل الطبي',
    medication: 'الدواء',
    
    // Goal related
    goal: 'الهدف',
    goals: 'الأهداف',
    goalSetting: 'وضع الأهداف',
    goalTracking: 'تتبع الأهداف',
    
    // Progress related
    progressTracking: 'تتبع التقدم',
    progressReport: 'تقرير التقدم',
    
    // AI related
    ai: 'الذكاء الاصطناعي',
    aiAssistant: 'المساعد الذكي',
    aiRecommendation: 'توصية ذكية',
    
    // Notification related
    notification: 'الإشعار',
    notifications: 'الإشعارات',
    reminder: 'التذكير',
    reminders: 'التذكيرات',
    
    // Privacy related
    privacy: 'الخصوصية',
    privacySettings: 'إعدادات الخصوصية',
    dataProtection: 'حماية البيانات',
    
    // Sync related
    sync: 'المزامنة',
    syncing: 'جاري المزامنة',
    syncComplete: 'اكتملت المزامنة',
    
    // Error messages
    errorOccurred: 'حدث خطأ',
    tryAgain: 'حاول مرة أخرى',
    connectionError: 'خطأ في الاتصال',
    
    // Success messages
    successMessage: 'تم بنجاح',
    savedSuccessfully: 'تم الحفظ بنجاح',
    updatedSuccessfully: 'تم التحديث بنجاح',
    
    // Additional terms
    viewRecords: 'عرض السجلات',
    errorText: 'نص الخطأ',
    userNotFound: 'المستخدم غير موجود',
    
    // Settings Screen specific
    resetSettingsConfirm: 'هل أنت متأكد من أنك تريد إعادة تعيين جميع الإعدادات إلى الافتراضية؟',
    clearCacheConfirm: 'هل أنت متأكد من أنك تريد مسح ذاكرة التخزين المؤقت للتطبيق؟',
    clear: 'مسح',
    reset: 'إعادة تعيين',
    settingsResetSuccess: 'تم إعادة تعيين الإعدادات إلى الافتراضية',
    cacheCleared: 'تم مسح ذاكرة التخزين المؤقت بنجاح',
    failedToClearCache: 'فشل في مسح ذاكرة التخزين المؤقت',
    
    // QR Code related
    generateQRCode: 'إنشاء رمز QR',
    qrCodeGenerated: 'تم إنشاء رمز QR',
    shareQRCode: 'مشاركة رمز QR',
    scanQRCode: 'مسح رمز QR',
    qrCodeError: 'خطأ في إنشاء رمز QR',
    
    // Health Passport specific
    healthPassportTitle: 'جواز الصحة',
    blockchainSecured: 'محمي بالبلوك تشين',
    universalAccess: 'وصول عالمي',
    hipaaCompliant: 'متوافق مع HIPAA',
    personalInformation: 'المعلومات الشخصية',
    emergencyContact: 'جهة الاتصال في حالات الطوارئ',
    currentVitalSigns: 'العلامات الحيوية الحالية',
    currentMedications: 'الأدوية الحالية',
    medicalRecords: 'السجلات الطبية',
    dataSharingAccess: 'مشاركة البيانات والوصول',
    recentAccessLog: 'سجل الوصول الأخير',
    sharingPermissions: 'أذونات المشاركة',
    emergencyServices: 'خدمات الطوارئ',
    fullAccessDuringEmergencies: 'وصول كامل أثناء حالات الطوارئ',
    primaryCarePhysician: 'طبيب الرعاية الأولية',
    fullMedicalHistoryAccess: 'وصول كامل للتاريخ الطبي',
    specialists: 'الأخصائيون',
    relevantRecordsOnly: 'السجلات ذات الصلة فقط',
    managePermissions: 'إدارة الأذونات',
    exportHealthData: 'تصدير البيانات الصحية',
    downloadCompleteHealthPassport: 'تحميل جواز الصحة الكامل للسجلات الشخصية أو المشاركة مع مقدمي الخدمة الجدد.',
    exportPDF: 'تصدير PDF',
    shareSecurely: 'مشاركة آمنة',
    bloodType: 'فصيلة الدم',
    allergies: 'الحساسية',
    spouse: 'الزوج/الزوجة',
    relationship: 'العلاقة',
    phone: 'الهاتف',
    updated: 'محدث',
    bmi: 'مؤشر كتلة الجسم',
    prescribedBy: 'وصفه',
    selfAdministered: 'إدارة ذاتية',
    labResults: 'نتائج المختبر',
    vaccination: 'التطعيم',
    prescription: 'الوصفة الطبية',
    routineConsultation: 'استشارة روتينية',
    labResultsUpload: 'رفع نتائج المختبر',
    addMedicalRecord: 'إضافة سجل طبي',
    controlWhoCanAccess: 'تحكم في من يمكنه الوصول إلى معلوماتك الصحية',
    accessor: 'الوصول',
    purpose: 'الغرض',
    dataAccessed: 'البيانات المُتاحة',
    active: 'نشط',
    download: 'تحميل',
    share: 'مشاركة',
    overview: 'نظرة عامة',
    records: 'السجلات',
    sharing: 'المشاركة',
    quickAccessQR: 'رمز QR للوصول السريع',
  },
  English: {
    // Settings
    settings: 'Settings',
    appSettings: 'App Settings',
    appearance: 'Appearance',
    darkMode: 'Dark Mode',
    language: 'Language',
    units: 'Units',
    audioHaptics: 'Audio & Haptics',
    soundEffects: 'Sound Effects',
    hapticFeedback: 'Haptic Feedback',
    dataSync: 'Data & Sync',
    autoSync: 'Auto Sync',
    offlineMode: 'Offline Mode',
    highQualityImages: 'High Quality Images',
    backgroundRefresh: 'Background Refresh',
    advanced: 'Advanced',
    betaFeatures: 'Beta Features',
    clearCache: 'Clear Cache',
    resetSettings: 'Reset Settings',
    appInformation: 'App Information',
    version: 'Version',
    build: 'Build',
    lastUpdated: 'Last Updated',
    
    // Common
    home: 'Home',
    profile: 'Profile',
    health: 'Health',
    fitness: 'Fitness',
    wellness: 'Wellness',
    aiChat: 'AI Chat',
    back: 'Back',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    view: 'View',
    start: 'Start',
    complete: 'Complete',
    next: 'Next',
    previous: 'Previous',
    loading: 'Loading',
    error: 'Error',
    success: 'Success',
    user: 'User',
    
    // Home Screen
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    todaysOverview: "Today's Overview",
    activityRings: 'Activity Rings',
    closeYourRings: 'Close your rings today',
    activeGoals: 'Active Goals',
    noActiveGoals: 'No active goals',
    setFirstGoal: 'Set your first goal to start your wellness journey',
    createGoal: 'Create Goal',
    quickActions: 'Quick Actions',
    healthCheck: 'Health Check',
    logVitals: 'Log vitals',
    startWorkout: 'Start Workout',
    getMoving: 'Get moving',
    mindfulness: 'Mindfulness',
    findPeace: 'Find peace',
    aiCoach: 'AI Coach',
    getAdvice: 'Get advice',
    upcoming: 'Upcoming',
    viewCalendar: 'View Calendar',
    doctorAppointment: 'Doctor Appointment',
    workoutSession: 'Workout Session',
    
    // Profile Screen
    yourWellnessJourney: 'Your wellness journey',
    healthOverview: 'Health Overview',
    avgHeartRate: 'Avg Heart Rate',
    dailySteps: 'Daily Steps',
    moodToday: 'Mood Today',
    achievements: 'Achievements',
    goalsProgress: 'Goals Progress',
    overallProgress: 'Overall Progress',
    goalsCompleted: 'goals completed',
    noActiveGoalsProfile: 'No active goals',
    setFirstGoalProfile: 'Set your first goal to start tracking your progress',
    profileSettings: 'Profile Settings',
    editProfile: 'Edit Profile',
    updatePersonalInfo: 'Update your personal information',
    healthPassport: 'Health Passport',
    viewHealthSummary: 'View your health summary',
    viewWellnessMilestones: 'View your wellness milestones',
    appSettingsDesc: 'Notifications, privacy, and more',
    recentAchievements: 'Recent Achievements',
    viewAll: 'View All',
    goalAchiever: 'Goal Achiever',
    completedFirstGoal: 'Completed your first wellness goal!',
    consistencyMaster: 'Consistency Master',
    sevenDayStreak: 'Maintained a 7-day streak of daily check-ins',
    
    // Health Screen
    yourWellnessDashboard: 'Your wellness dashboard',
    healthStatus: 'Health Status',
    allSystemsGood: 'All systems looking good',
    healthScore: 'Health Score',
    riskFactors: 'Risk Factors',
    trackedMetrics: 'Tracked Metrics',
    symptomChecker: 'Symptom Checker',
    aiAssessment: 'AI assessment',
    virtualConsult: 'Virtual Consult',
    talkToDoctor: 'Talk to doctor',
    aiNavigator: 'AI Navigator',
    healthGuidance: 'Health guidance',
    vitalSigns: 'Vital Signs',
    addReading: 'Add Reading',
    heartRate: 'Heart Rate',
    bloodPressure: 'Blood Pressure',
    weight: 'Weight',
    sleepQuality: 'Sleep Quality',
    upcomingAppointments: 'Upcoming Appointments',
    seeAll: 'See All',
    noUpcomingAppointments: 'No upcoming appointments',
    scheduleHealthCheckup: 'Schedule your next health checkup or consultation',
    scheduleAppointment: 'Schedule Appointment',
    medications: 'Medications',
    manage: 'Manage',
    noActiveMedications: 'No active medications',
    addMedicationsTrack: 'Add your medications to track dosages and schedules',
    addMedication: 'Add Medication',
    healthInsights: 'Health Insights',
    greatProgress: 'Great Progress!',
    heartRateHealthy: 'Your heart rate has been consistently in the healthy range this week. Keep up the good work with your cardio exercises!',
    sleepOptimization: 'Sleep Optimization',
    trackSleepQuality: 'Consider tracking your sleep quality to better understand your energy patterns and overall health.',
    
    // Fitness Screen
    stayStrongHealthy: 'Stay strong, stay healthy',
    caloriesBurned: 'Calories Burned',
    activeMinutes: 'Active Minutes',
    workouts: 'Workouts',
    strength: 'Strength',
    quickStart: 'Quick Start',
    aiTrainer: 'AI Trainer',
    personalizedWorkouts: 'Personalized workouts',
    calorieScanner: 'Calorie Scanner',
    trackNutrition: 'Track nutrition',
    groupTraining: 'Group Training',
    joinOthers: 'Join others',
    assessment: 'Assessment',
    testFitness: 'Test fitness',
    todaysWorkouts: "Today's Workouts",
    noWorkoutsScheduled: 'No workouts scheduled',
    startFitnessJourney: 'Start your fitness journey with a quick workout',
    scheduleWorkout: 'Schedule Workout',
    progressMetrics: 'Progress Metrics',
    featuredTrainers: 'Featured Trainers',
    noTrainersAvailable: 'No trainers available',
    connectProfessionalTrainers: 'Connect with professional trainers to reach your goals',
    findTrainers: 'Find Trainers',
    insights: 'Insights',
    excellentProgress: 'Excellent Progress!',
    increasedWorkoutIntensity: 'You have increased your workout intensity by 15% this week. Keep pushing your limits!',
    recoveryTime: 'Recovery Time',
    considerRestDays: 'Consider adding more rest days between intense workouts for optimal recovery.',
    viewInsights: 'View Insights',
    burnedToday: 'burned today',
    activeTime: 'active time',
    bookSession: 'Book Session',
    
    // Wellness Screen
    mindBodySoul: 'Mind, body, and soul',
    howAreYouFeeling: 'How are you feeling?',
    feelingGood: 'Feeling good',
    tapToLogMood: 'Tap to log your mood',
    energy: 'Energy',
    activeHabits: 'Active Habits',
    checkIn: 'Check-in',
    logMood: 'Log Mood',
    trackFeelings: 'Track feelings',
    nutritionScanner: 'Nutrition Scanner',
    trackFood: 'Track food',
    sleepTracker: 'Sleep Tracker',
    monitorRest: 'Monitor rest',
    breathe: 'Breathe',
    relaxMind: 'Relax mind',
    wellnessScores: 'Wellness Scores',
    energyLevel: 'Energy Level',
    resilience: 'Resilience',
    improving: 'Improving',
    declining: 'Declining',
    stable: 'Stable',
    dailyCheckIn: 'Daily Check-in',
    readyForCheckIn: 'Ready for your daily check-in?',
    reflectOnDay: 'Take a moment to reflect on your day and track your wellness',
    checkInComplete: 'Check-in Complete!',
    completedDailyCheckIn: 'Great job completing your daily wellness check-in. Keep up the momentum!',
    todaysHabits: "Today's Habits",
    addHabit: 'Add Habit',
    noActiveHabitsWellness: 'No active habits',
    buildHealthyHabits: 'Build healthy habits to improve your daily wellness',
    createFirstHabit: 'Create Your First Habit',
    dayStreak: 'day streak',
    moodImprovement: 'Mood Improvement',
    moodConsistentlyPositive: 'Your mood has been consistently positive this week. Keep up the great work with your wellness routine!',
    energyBoost: 'Energy Boost',
    tryMorningMeditation: 'Try adding a 10-minute morning meditation to boost your energy levels throughout the day.',
    
    // AI Chat Screen
    aiHealthCoach: 'AI Health Coach',
    personalWellnessAssistant: 'Your personal wellness assistant',
    oneHealthAI: 'One Health AI',
    onlineReady: 'Online & Ready',
    personalizedInsights: 'Personalized Insights',
    aiThinking: 'AI is thinking...',
    askAnythingHealth: 'Ask me anything about your health',
    goalProgress: 'Goal Progress',
    motivation: 'Motivation',
    newPlan: 'New Plan',
    dailyFocus: 'Daily Focus',
    
    // Common Status
    normal: 'normal',
    elevated: 'elevated',
    good: 'good',
    excellent: 'excellent',
    okay: 'okay',
    low: 'low',
    terrible: 'terrible',
    
    // Units
    bpm: 'bpm',
    mmHg: 'mmHg',
    kg: 'kg',
    score: 'score',
    kcal: 'kcal',
    min: 'min',
    steps: 'steps',
    earned: 'earned',
    feeling: 'feeling',
    
    // Time
    today: 'today',
    yesterday: 'yesterday',
    thisWeek: 'this week',
    lastNight: 'last night',
    daysAgo: 'days ago',
    weekAgo: 'week ago',
    
    // Login & Onboarding
    signInWithPhone: 'Sign in with Phone',
    sendVerificationCode: 'Send Verification Code',
    enterVerificationCode: 'Enter Verification Code',
    verifyAndContinue: 'Verify & Continue',
    phoneNumber: 'Phone Number',
    verificationCode: 'Verification Code',
    resendCode: 'Resend Code',
    didntReceiveCode: "Didn't receive the code?",
    letsGetToKnowYou: "Let's get to know you",
    personalizeHealthJourney: "We'll use this to personalize your health journey",
    fullName: 'Full Name',
    enterYourName: 'Enter your name',
    nationalId: 'National ID',
    email: 'Email',
    basicInformation: 'Basic information',
    accurateRecommendations: 'This helps us provide more accurate recommendations',
    age: 'Age',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    preferNotToSay: 'Prefer not to say',
    bodyMeasurements: 'Body measurements',
    calculateFitnessNeeds: "We'll use this to calculate your fitness needs",
    height: 'Height',
    enterYourHeight: 'Enter your height',
    enterYourWeight: 'Enter your weight',
    uploadMedicalReports: 'Upload Medical Reports',
    whatAreYourGoals: 'What are your goals?',
    selectAllThatApply: 'Select all that apply to you',
    loseWeight: 'Lose weight',
    buildMuscle: 'Build muscle',
    improveFitness: 'Improve fitness',
    increaseStrength: 'Increase strength',
    improveFlex: 'Improve flexibility',
    reduceStress: 'Reduce stress',
    betterSleepOnboarding: 'Better sleep',
    moreEnergy: 'More energy',
    medicalHistory: 'Medical history',
    understandHealthBackground: 'Help us understand your health background',
    anyConditions: 'Do you have any of these conditions?',
    fitnessLevel: 'Fitness level',
    rightWorkoutPlan: 'This helps us create the right workout plan',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    newToExercise: 'New to exercise or returning after a break',
    exerciseRegularly: 'Exercise 2-3 times per week regularly',
    exerciseConsistently: 'Exercise 4+ times per week consistently',
    lifestyleInformation: 'Lifestyle information',
    dailyHabits: 'Tell us about your daily habits',
    averageSleepHours: 'Average sleep hours per night',
    currentStressLevel: 'Current stress level (1-10)',
    dietaryPreferences: 'Dietary preferences',
    occupation: 'Occupation',
    behavioralPreferences: 'Behavioral preferences',
    howMotivated: 'Help us understand how you like to be motivated',
    whatMotivatesYou: 'What motivates you most?',
    competitionChallenges: 'Competition & Challenges',
    teamCommunity: 'Team & Community',
    personalAchievementMotivation: 'Personal Achievement',
    gentleSupport: 'Gentle Support',
    preferredWorkoutTime: 'Preferred workout time',
    morning: 'Morning',
    afternoon: 'Afternoon',
    evening: 'Evening',
    flexible: 'Flexible',
    reminderStyle: 'Reminder style',
    gentle: 'Gentle',
    firm: 'Firm',
    motivational: 'Motivational',
    goalPersonalization: 'Goal personalization',
    customizeGoalSetting: "Let's customize your goal-setting experience",
    primaryFocus: "What's your primary focus?",
    balancedFocus: 'Balanced',
    whatMotivatesYouSelect: 'What motivates you? (Select all that apply)',
    healthImprovement: 'Health improvement',
    weightManagement: 'Weight management',
    stressRelief: 'Stress relief',
    betterSleepGoal: 'Better sleep',
    increasedEnergy: 'Increased energy',
    socialConnection: 'Social connection',
    personalAchievementGoal: 'Personal achievement',
    diseasePrevention: 'Disease prevention',
    preferredGoalTimeframe: 'Preferred goal timeframe',
    shortTerm: 'Short (1-3 months)',
    mediumTerm: 'Medium (3-6 months)',
    longTerm: 'Long (6+ months)',
    trackingDetail: 'How much detail do you want in tracking?',
    detailed: 'Detailed',
    simple: 'Simple',
    minimal: 'Minimal',
    specificGoals: 'Specific goals',
    personalizedGoalsSetup: "Let's set up your personalized goals",
    weightGoal: 'Weight Goal',
    loseWeightGoal: 'Lose weight',
    gainWeight: 'Gain weight',
    maintainWeight: 'Maintain weight',
    reduceBodyWeight: 'Reduce body weight',
    increaseBodyWeight: 'Increase body weight',
    keepCurrentWeight: 'Keep current weight',
    targetWeight: 'Target Weight',
    timeframeMonths: 'Timeframe (months)',
    energyGoal: 'Energy Goal',
    increaseEnergyGoal: 'Increase energy',
    stabilizeEnergy: 'Stabilize energy',
    betterMorningEnergy: 'Better morning energy',
    feelMoreEnergetic: 'Feel more energetic throughout the day',
    avoidEnergyCrashes: 'Avoid energy crashes and maintain steady levels',
    wakeUpRefreshed: 'Wake up feeling more refreshed',
    targetEnergyLevel: 'Target Energy Level (1-10)',
    stressReductionGoal: 'Stress Reduction Goal',
    targetStressLevel: 'Target stress level (1-10, lower is better)',
    continueBtn: 'Continue',
    completeSetup: 'Complete Setup',
    
    // Additional common terms
    camera: 'Camera',
    gallery: 'Gallery',
    optional: 'Optional',
    sending: 'Sending',
    verifying: 'Verifying',
    encrypted: 'Encrypted',
    neverShared: 'Never shared',
    thirdParties: 'Third parties',
    phoneEncrypted: 'Your phone number is encrypted and never shared with third parties',
    sendingCode: 'Sending code...',
    verifyingCode: 'Verifying...',
    sentCodeTo: 'We sent a 4-digit code to',
    
    // Additional UI elements
    distance: 'Distance',
    km: 'km',
    activeTimeShort: 'Active time',
    
    // Additional wellness terms
    meditation: 'Meditation',
    morningCalm: 'Morning calm',
    stressReliefMeditation: 'Stress relief',
    sleepStories: 'Sleep stories',
    
    // Additional fitness terms
    pushUps: 'Push-ups',
    squats: 'Squats',
    customWorkout: 'Custom workout',
    
    // Additional health terms
    provider: 'Provider',
    appointment: 'Appointment',
    dosage: 'Dosage',
    frequency: 'Frequency',
    
    // Additional profile terms
    totalGoals: 'Total goals',
    completedGoals: 'Completed goals',
    progressPercentage: 'Progress percentage',
    
    // Additional onboarding terms
    chronicConditions: 'Chronic conditions',
    fitnessLimitations: 'Fitness limitations',
    ehrSystem: 'EHR system',
    connectEHR: 'Connect EHR',
    ehrConnected: 'EHR connected',
    primaryCareProvider: 'Primary care provider',
    lastPhysicalExam: 'Last physical exam',
    
    // Status messages
    planCreated: 'Plan created!',
    personalizedPlanCreated: 'Your personalized plan has been created and added to your profile. You can track your progress in the Health section.',
    failedToCreatePlan: 'Failed to create plan. Please try again.',
    
    // Additional common terms
    of: 'of',
    at: 'at',
    on: 'on',
    and: 'and',
    or: 'or',
    with: 'with',
    without: 'without',
    for: 'for',
    from: 'from',
    to: 'to',
    in: 'in',
    
    // Sleep related
    sleep: 'Sleep',
    sleepHours: 'Sleep hours',
    sleepQualityScore: 'Sleep quality score',
    
    // Mood related
    mood: 'Mood',
    moodScore: 'Mood score',
    moodTracking: 'Mood tracking',
    
    // Exercise related
    exercise: 'Exercise',
    exercises: 'Exercises',
    workout: 'Workout',
    workoutPlan: 'Workout plan',
    
    // Nutrition related
    nutrition: 'Nutrition',
    nutritionPlan: 'Nutrition plan',
    calories: 'Calories',
    
    // Medical related
    medical: 'Medical',
    medicalRecord: 'Medical record',
    medication: 'Medication',
    
    // Goal related
    goal: 'Goal',
    goals: 'Goals',
    goalSetting: 'Goal setting',
    goalTracking: 'Goal tracking',
    
    // Progress related
    progressTracking: 'Progress tracking',
    progressReport: 'Progress report',
    
    // AI related
    ai: 'AI',
    aiAssistant: 'AI assistant',
    aiRecommendation: 'AI recommendation',
    
    // Notification related
    notification: 'Notification',
    notifications: 'Notifications',
    reminder: 'Reminder',
    reminders: 'Reminders',
    
    // Privacy related
    privacy: 'Privacy',
    privacySettings: 'Privacy settings',
    dataProtection: 'Data protection',
    
    // Sync related
    sync: 'Sync',
    syncing: 'Syncing',
    syncComplete: 'Sync complete',
    
    // Error messages
    errorOccurred: 'An error occurred',
    tryAgain: 'Try again',
    connectionError: 'Connection error',
    
    // Success messages
    successMessage: 'Success',
    savedSuccessfully: 'Saved successfully',
    updatedSuccessfully: 'Updated successfully',
    
    // Additional terms
    viewDetails: 'View Details',
    viewRecords: 'View records',
    minutes: 'minutes',
    errorText: 'Error text',
    userNotFound: 'User not found',
    
    // Settings Screen specific
    resetSettingsConfirm: 'Are you sure you want to reset all settings to default?',
    clearCacheConfirm: 'Are you sure you want to clear the app cache?',
    clear: 'Clear',
    reset: 'Reset',
    settingsResetSuccess: 'Settings have been reset to default',
    cacheCleared: 'Cache cleared successfully',
    failedToClearCache: 'Failed to clear cache',
    
    // QR Code related
    generateQRCode: 'Generate QR Code',
    qrCodeGenerated: 'QR Code Generated',
    shareQRCode: 'Share QR Code',
    scanQRCode: 'Scan QR Code',
    qrCodeError: 'Error generating QR code',
    
    // Health Passport specific
    healthPassportTitle: 'Health Passport',
    blockchainSecured: 'Blockchain-secured',
    universalAccess: 'Universal Access',
    hipaaCompliant: 'HIPAA Compliant',
    personalInformation: 'Personal Information',
    emergencyContact: 'Emergency Contact',
    currentVitalSigns: 'Current Vital Signs',
    currentMedications: 'Current Medications',
    medicalRecords: 'Medical Records',
    dataSharingAccess: 'Data Sharing & Access',
    recentAccessLog: 'Recent Access Log',
    sharingPermissions: 'Sharing Permissions',
    emergencyServices: 'Emergency Services',
    fullAccessDuringEmergencies: 'Full access during emergencies',
    primaryCarePhysician: 'Primary Care Physician',
    fullMedicalHistoryAccess: 'Full medical history access',
    specialists: 'Specialists',
    relevantRecordsOnly: 'Relevant records only',
    managePermissions: 'Manage Permissions',
    exportHealthData: 'Export Health Data',
    downloadCompleteHealthPassport: 'Download your complete health passport for personal records or sharing with new providers.',
    exportPDF: 'Export PDF',
    shareSecurely: 'Share Securely',
    bloodType: 'Blood Type',
    allergies: 'Allergies',
    spouse: 'Spouse',
    relationship: 'Relationship',
    phone: 'Phone',
    updated: 'Updated',
    bmi: 'BMI',
    prescribedBy: 'Prescribed by',
    selfAdministered: 'Self-administered',
    labResults: 'Lab Results',
    vaccination: 'Vaccination',
    prescription: 'Prescription',
    routineConsultation: 'Routine consultation',
    labResultsUpload: 'Lab results upload',
    addMedicalRecord: 'Add Medical Record',
    controlWhoCanAccess: 'Control who can access your health information',
    accessor: 'Accessor',
    purpose: 'Purpose',
    dataAccessed: 'Data Accessed',
    active: 'active',
    download: 'Download',
    share: 'Share',
    overview: 'Overview',
    records: 'Records',
    sharing: 'Sharing',
    quickAccessQR: 'QR code for quick access',
  },
  Spanish: {
    // Settings
    settings: 'Configuración',
    appSettings: 'Configuración de la App',
    appearance: 'Apariencia',
    darkMode: 'Modo Oscuro',
    language: 'Idioma',
    units: 'Unidades',
    audioHaptics: 'Audio y Hápticos',
    soundEffects: 'Efectos de Sonido',
    hapticFeedback: 'Retroalimentación Háptica',
    dataSync: 'Datos y Sincronización',
    autoSync: 'Sincronización Automática',
    offlineMode: 'Modo Sin Conexión',
    highQualityImages: 'Imágenes de Alta Calidad',
    backgroundRefresh: 'Actualización en Segundo Plano',
    advanced: 'Avanzado',
    betaFeatures: 'Características Beta',
    clearCache: 'Limpiar Caché',
    resetSettings: 'Restablecer Configuración',
    appInformation: 'Información de la App',
    version: 'Versión',
    build: 'Compilación',
    lastUpdated: 'Última Actualización',
    
    // Common
    home: 'Inicio',
    profile: 'Perfil',
    health: 'Salud',
    fitness: 'Fitness',
    wellness: 'Bienestar',
    aiChat: 'Chat IA',
    back: 'Atrás',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    add: 'Agregar',
    view: 'Ver',
    start: 'Comenzar',
    complete: 'Completar',
    next: 'Siguiente',
    previous: 'Anterior',
    loading: 'Cargando',
    error: 'Error',
    success: 'Éxito',
    user: 'Usuario',
    
    // Home Screen
    goodMorning: 'Buenos días',
    goodAfternoon: 'Buenas tardes',
    goodEvening: 'Buenas noches',
    todaysOverview: 'Resumen de Hoy',
    activityRings: 'Anillos de Actividad',
    closeYourRings: 'Cierra tus anillos hoy',
    activeGoals: 'Objetivos Activos',
    noActiveGoals: 'Sin objetivos activos',
    setFirstGoal: 'Establece tu primer objetivo para comenzar tu viaje de bienestar',
    createGoal: 'Crear Objetivo',
    quickActions: 'Acciones Rápidas',
    healthCheck: 'Chequeo de Salud',
    logVitals: 'Registrar signos vitales',
    startWorkout: 'Comenzar Entrenamiento',
    getMoving: 'Ponte en movimiento',
    mindfulness: 'Atención Plena',
    findPeace: 'Encuentra la paz',
    aiCoach: 'Entrenador IA',
    getAdvice: 'Obtener consejo',
    upcoming: 'Próximo',
    viewCalendar: 'Ver Calendario',
    doctorAppointment: 'Cita Médica',
    workoutSession: 'Sesión de Entrenamiento',
    
    // Profile Screen
    yourWellnessJourney: 'Tu viaje de bienestar',
    healthOverview: 'Resumen de Salud',
    avgHeartRate: 'Frecuencia Cardíaca Promedio',
    dailySteps: 'Pasos Diarios',
    moodToday: 'Estado de Ánimo Hoy',
    achievements: 'Logros',
    goalsProgress: 'Progreso de Objetivos',
    overallProgress: 'Progreso General',
    goalsCompleted: 'objetivos completados',
    noActiveGoalsProfile: 'Sin objetivos activos',
    setFirstGoalProfile: 'Establece tu primer objetivo para comenzar a rastrear tu progreso',
    profileSettings: 'Configuración del Perfil',
    editProfile: 'Editar Perfil',
    updatePersonalInfo: 'Actualizar tu información personal',
    healthPassport: 'Pasaporte de Salud',
    viewHealthSummary: 'Ver tu resumen de salud',
    viewWellnessMilestones: 'Ver tus hitos de bienestar',
    appSettingsDesc: 'Notificaciones, privacidad y más',
    recentAchievements: 'Logros Recientes',
    viewAll: 'Ver Todo',
    goalAchiever: 'Logrador de Objetivos',
    completedFirstGoal: '¡Completaste tu primer objetivo de bienestar!',
    consistencyMaster: 'Maestro de la Consistencia',
    sevenDayStreak: 'Mantuviste una racha de 7 días de registros diarios',
    
    // Health Screen
    yourWellnessDashboard: 'Tu panel de bienestar',
    healthStatus: 'Estado de Salud',
    allSystemsGood: 'Todos los sistemas se ven bien',
    healthScore: 'Puntuación de Salud',
    riskFactors: 'Factores de Riesgo',
    trackedMetrics: 'Métricas Rastreadas',
    symptomChecker: 'Verificador de Síntomas',
    aiAssessment: 'Evaluación IA',
    virtualConsult: 'Consulta Virtual',
    talkToDoctor: 'Hablar con el doctor',
    aiNavigator: 'Navegador IA',
    healthGuidance: 'Orientación de salud',
    vitalSigns: 'Signos Vitales',
    addReading: 'Agregar Lectura',
    heartRate: 'Frecuencia Cardíaca',
    bloodPressure: 'Presión Arterial',
    weight: 'Peso',
    sleepQuality: 'Calidad del Sueño',
    upcomingAppointments: 'Citas Próximas',
    seeAll: 'Ver Todo',
    noUpcomingAppointments: 'Sin citas próximas',
    scheduleHealthCheckup: 'Programa tu próximo chequeo de salud o consulta',
    scheduleAppointment: 'Programar Cita',
    medications: 'Medicamentos',
    manage: 'Gestionar',
    noActiveMedications: 'Sin medicamentos activos',
    addMedicationsTrack: 'Agrega tus medicamentos para rastrear dosis y horarios',
    addMedication: 'Agregar Medicamento',
    healthInsights: 'Perspectivas de Salud',
    greatProgress: '¡Gran Progreso!',
    heartRateHealthy: 'Tu frecuencia cardíaca ha estado consistentemente en el rango saludable esta semana. ¡Sigue con el buen trabajo con tus ejercicios cardiovasculares!',
    sleepOptimization: 'Optimización del Sueño',
    trackSleepQuality: 'Considera rastrear tu calidad de sueño para entender mejor tus patrones de energía y salud general.',
    
    // Fitness Screen
    stayStrongHealthy: 'Mantente fuerte, mantente saludable',
    caloriesBurned: 'Calorías Quemadas',
    activeMinutes: 'Minutos Activos',
    workouts: 'Entrenamientos',
    strength: 'Fuerza',
    quickStart: 'Inicio Rápido',
    aiTrainer: 'Entrenador IA',
    personalizedWorkouts: 'Entrenamientos personalizados',
    calorieScanner: 'Escáner de Calorías',
    trackNutrition: 'Rastrear nutrición',
    groupTraining: 'Entrenamiento Grupal',
    joinOthers: 'Únete a otros',
    assessment: 'Evaluación',
    testFitness: 'Probar condición física',
    todaysWorkouts: 'Entrenamientos de Hoy',
    noWorkoutsScheduled: 'Sin entrenamientos programados',
    startFitnessJourney: 'Comienza tu viaje de fitness con un entrenamiento rápido',
    scheduleWorkout: 'Programar Entrenamiento',
    progressMetrics: 'Métricas de Progreso',
    featuredTrainers: 'Entrenadores Destacados',
    noTrainersAvailable: 'Sin entrenadores disponibles',
    connectProfessionalTrainers: 'Conéctate con entrenadores profesionales para alcanzar tus objetivos',
    findTrainers: 'Encontrar Entrenadores',
    insights: 'Perspectivas',
    excellentProgress: '¡Progreso Excelente!',
    increasedWorkoutIntensity: 'Has aumentado la intensidad de tu entrenamiento en un 15% esta semana. ¡Sigue empujando tus límites!',
    recoveryTime: 'Tiempo de Recuperación',
    considerRestDays: 'Considera agregar más días de descanso entre entrenamientos intensos para una recuperación óptima.',
    viewInsights: 'Ver Perspectivas',
    burnedToday: 'quemadas hoy',
    activeTime: 'tiempo activo',
    bookSession: 'Reservar Sesión',
    
    // Wellness Screen
    mindBodySoul: 'Mente, cuerpo y alma',
    howAreYouFeeling: '¿Cómo te sientes?',
    feelingGood: 'Sintiéndome bien',
    tapToLogMood: 'Toca para registrar tu estado de ánimo',
    energy: 'Energía',
    activeHabits: 'Hábitos Activos',
    checkIn: 'Registro',
    logMood: 'Registrar Estado de Ánimo',
    trackFeelings: 'Rastrear sentimientos',
    nutritionScanner: 'Escáner de Nutrición',
    trackFood: 'Rastrear comida',
    sleepTracker: 'Rastreador de Sueño',
    monitorRest: 'Monitorear descanso',
    breathe: 'Respirar',
    relaxMind: 'Relajar la mente',
    wellnessScores: 'Puntuaciones de Bienestar',
    energyLevel: 'Nivel de Energía',
    resilience: 'Resistencia',
    improving: 'Mejorando',
    declining: 'Declinando',
    stable: 'Estable',
    dailyCheckIn: 'Registro Diario',
    readyForCheckIn: '¿Listo para tu registro diario?',
    reflectOnDay: 'Tómate un momento para reflexionar sobre tu día y rastrear tu bienestar',
    checkInComplete: '¡Registro Completo!',
    completedDailyCheckIn: 'Excelente trabajo completando tu registro diario de bienestar. ¡Mantén el impulso!',
    todaysHabits: 'Hábitos de Hoy',
    addHabit: 'Agregar Hábito',
    noActiveHabitsWellness: 'Sin hábitos activos',
    buildHealthyHabits: 'Construye hábitos saludables para mejorar tu bienestar diario',
    createFirstHabit: 'Crear Tu Primer Hábito',
    dayStreak: 'racha de días',
    moodImprovement: 'Mejora del Estado de Ánimo',
    moodConsistentlyPositive: 'Tu estado de ánimo ha sido consistentemente positivo esta semana. ¡Sigue con el gran trabajo con tu rutina de bienestar!',
    energyBoost: 'Impulso de Energía',
    tryMorningMeditation: 'Intenta agregar una meditación matutina de 10 minutos para impulsar tus niveles de energía durante todo el día.',
    
    // AI Chat Screen
    aiHealthCoach: 'Entrenador de Salud IA',
    personalWellnessAssistant: 'Tu asistente personal de bienestar',
    oneHealthAI: 'IA de Una Salud',
    onlineReady: 'En línea y Listo',
    personalizedInsights: 'Perspectivas Personalizadas',
    aiThinking: 'La IA está pensando...',
    askAnythingHealth: 'Pregúntame cualquier cosa sobre tu salud',
    goalProgress: 'Progreso del Objetivo',
    motivation: 'Motivación',
    newPlan: 'Nuevo Plan',
    dailyFocus: 'Enfoque Diario',
    
    // Common Status
    normal: 'normal',
    elevated: 'elevado',
    good: 'bueno',
    excellent: 'excelente',
    okay: 'bien',
    low: 'bajo',
    terrible: 'terrible',
    
    // Units
    bpm: 'lpm',
    mmHg: 'mmHg',
    kg: 'kg',
    score: 'puntuación',
    kcal: 'kcal',
    min: 'min',
    steps: 'pasos',
    earned: 'ganado',
    feeling: 'sintiendo',
    
    // Time
    today: 'hoy',
    yesterday: 'ayer',
    thisWeek: 'esta semana',
    lastNight: 'anoche',
    daysAgo: 'días atrás',
    weekAgo: 'hace una semana',
    
    // Login & Onboarding
    signInWithPhone: 'Iniciar sesión con teléfono',
    sendVerificationCode: 'Enviar código de verificación',
    enterVerificationCode: 'Ingresa el código de verificación',
    verifyAndContinue: 'Verificar y continuar',
    phoneNumber: 'Número de teléfono',
    verificationCode: 'Código de verificación',
    resendCode: 'Reenviar código',
    didntReceiveCode: '¿No recibiste el código?',
    letsGetToKnowYou: 'Conozcámonos',
    personalizeHealthJourney: 'Usaremos esto para personalizar tu viaje de salud',
    fullName: 'Nombre completo',
    enterYourName: 'Ingresa tu nombre',
    nationalId: 'Cédula Nacional',
    email: 'Correo electrónico',
    basicInformation: 'Información básica',
    accurateRecommendations: 'Esto nos ayuda a proporcionar recomendaciones más precisas',
    age: 'Edad',
    gender: 'Género',
    male: 'Masculino',
    female: 'Femenino',
    other: 'Otro',
    preferNotToSay: 'Prefiero no decir',
    bodyMeasurements: 'Medidas corporales',
    calculateFitnessNeeds: 'Usaremos esto para calcular tus necesidades de fitness',
    height: 'Altura',
    enterYourHeight: 'Ingresa tu altura',
    enterYourWeight: 'Ingresa tu peso',
    uploadMedicalReports: 'Subir informes médicos',
    whatAreYourGoals: '¿Cuáles son tus objetivos?',
    selectAllThatApply: 'Selecciona todo lo que se aplique a ti',
    loseWeight: 'Perder peso',
    buildMuscle: 'Construir músculo',
    improveFitness: 'Mejorar fitness',
    increaseStrength: 'Aumentar fuerza',
    improveFlex: 'Mejorar flexibilidad',
    reduceStress: 'Reducir estrés',
    betterSleepOnboarding: 'Mejor sueño',
    moreEnergy: 'Más energía',
    medicalHistory: 'Historial médico',
    understandHealthBackground: 'Ayúdanos a entender tu historial de salud',
    anyConditions: '¿Tienes alguna de estas condiciones?',
    fitnessLevel: 'Nivel de fitness',
    rightWorkoutPlan: 'Esto nos ayuda a crear el plan de entrenamiento correcto',
    beginner: 'Principiante',
    intermediate: 'Intermedio',
    advanced: 'Avanzado',
    newToExercise: 'Nuevo en el ejercicio o regresando después de un descanso',
    exerciseRegularly: 'Hago ejercicio 2-3 veces por semana regularmente',
    exerciseConsistently: 'Hago ejercicio 4+ veces por semana consistentemente',
    lifestyleInformation: 'Información de estilo de vida',
    dailyHabits: 'Cuéntanos sobre tus hábitos diarios',
    averageSleepHours: 'Promedio de horas de sueño por noche',
    currentStressLevel: 'Nivel de estrés actual (1-10)',
    dietaryPreferences: 'Preferencias dietéticas',
    occupation: 'Ocupación',
    behavioralPreferences: 'Preferencias de comportamiento',
    howMotivated: 'Ayúdanos a entender cómo te gusta ser motivado',
    whatMotivatesYou: '¿Qué te motiva más?',
    competitionChallenges: 'Competencia y desafíos',
    teamCommunity: 'Equipo y comunidad',
    personalAchievementMotivation: 'Logro personal',
    gentleSupport: 'Apoyo gentil',
    preferredWorkoutTime: 'Hora preferida de entrenamiento',
    morning: 'Mañana',
    afternoon: 'Tarde',
    evening: 'Noche',
    flexible: 'Flexible',
    reminderStyle: 'Estilo de recordatorio',
    gentle: 'Gentil',
    firm: 'Firme',
    motivational: 'Motivacional',
    goalPersonalization: 'Personalización de objetivos',
    customizeGoalSetting: 'Personalicemos tu experiencia de establecimiento de objetivos',
    primaryFocus: '¿Cuál es tu enfoque principal?',
    balancedFocus: 'Equilibrado',
    whatMotivatesYouSelect: '¿Qué te motiva? (Selecciona todo lo que aplique)',
    healthImprovement: 'Mejora de la salud',
    weightManagement: 'Manejo del peso',
    stressRelief: 'Alivio del estrés',
    betterSleepGoal: 'Mejor sueño',
    increasedEnergy: 'Energía aumentada',
    socialConnection: 'Conexión social',
    personalAchievementGoal: 'Logro personal',
    diseasePrevention: 'Prevención de enfermedades',
    preferredGoalTimeframe: 'Marco de tiempo preferido para objetivos',
    shortTerm: 'Corto (1-3 meses)',
    mediumTerm: 'Medio (3-6 meses)',
    longTerm: 'Largo (6+ meses)',
    trackingDetail: '¿Cuánto detalle quieres en el seguimiento?',
    detailed: 'Detallado',
    simple: 'Simple',
    minimal: 'Mínimo',
    specificGoals: 'Objetivos específicos',
    personalizedGoalsSetup: 'Configuremos tus objetivos personalizados',
    weightGoal: 'Objetivo de peso',
    loseWeightGoal: 'Perder peso',
    gainWeight: 'Ganar peso',
    maintainWeight: 'Mantener peso',
    reduceBodyWeight: 'Reducir peso corporal',
    increaseBodyWeight: 'Aumentar peso corporal',
    keepCurrentWeight: 'Mantener peso actual',
    targetWeight: 'Peso objetivo',
    timeframeMonths: 'Marco de tiempo (meses)',
    energyGoal: 'Objetivo de energía',
    increaseEnergyGoal: 'Aumentar energía',
    stabilizeEnergy: 'Estabilizar energía',
    betterMorningEnergy: 'Mejor energía matutina',
    feelMoreEnergetic: 'Sentirse más enérgico durante el día',
    avoidEnergyCrashes: 'Evitar caídas de energía y mantener niveles estables',
    wakeUpRefreshed: 'Despertar sintiéndose más refrescado',
    targetEnergyLevel: 'Nivel de energía objetivo (1-10)',
    stressReductionGoal: 'Objetivo de reducción de estrés',
    targetStressLevel: 'Nivel de estrés objetivo (1-10, menor es mejor)',
    continueBtn: 'Continuar',
    completeSetup: 'Completar configuración',
    
    // Additional common terms
    camera: 'Cámara',
    gallery: 'Galería',
    optional: 'Opcional',
    sending: 'Enviando',
    verifying: 'Verificando',
    encrypted: 'Encriptado',
    neverShared: 'Nunca compartido',
    thirdParties: 'Terceros',
    phoneEncrypted: 'Tu número de teléfono está encriptado y nunca se comparte con terceros',
    sendingCode: 'Enviando código...',
    verifyingCode: 'Verificando...',
    sentCodeTo: 'Enviamos un código de 4 dígitos a',
    
    // Additional UI elements
    distance: 'Distancia',
    km: 'km',
    activeTimeShort: 'Tiempo activo',
    
    // Additional wellness terms
    meditation: 'Meditación',
    morningCalm: 'Calma matutina',
    stressReliefMeditation: 'Alivio del estrés',
    sleepStories: 'Historias para dormir',
    
    // Additional fitness terms
    pushUps: 'Flexiones',
    squats: 'Sentadillas',
    customWorkout: 'Entrenamiento personalizado',
    
    // Additional health terms
    provider: 'Proveedor',
    appointment: 'Cita',
    dosage: 'Dosis',
    frequency: 'Frecuencia',
    
    // Additional profile terms
    totalGoals: 'Objetivos totales',
    completedGoals: 'Objetivos completados',
    progressPercentage: 'Porcentaje de progreso',
    
    // Additional onboarding terms
    chronicConditions: 'Condiciones crónicas',
    fitnessLimitations: 'Limitaciones de fitness',
    ehrSystem: 'Sistema EHR',
    connectEHR: 'Conectar EHR',
    ehrConnected: 'EHR conectado',
    primaryCareProvider: 'Proveedor de atención primaria',
    lastPhysicalExam: 'Último examen físico',
    
    // Status messages
    planCreated: '¡Plan creado!',
    personalizedPlanCreated: 'Tu plan personalizado ha sido creado y agregado a tu perfil. Puedes rastrear tu progreso en la sección de Salud.',
    failedToCreatePlan: 'Error al crear el plan. Por favor intenta de nuevo.',
    
    // Additional common terms
    of: 'de',
    at: 'en',
    on: 'en',
    and: 'y',
    or: 'o',
    with: 'con',
    without: 'sin',
    for: 'para',
    from: 'de',
    to: 'a',
    in: 'en',
    
    // Sleep related
    sleep: 'Sueño',
    sleepHours: 'Horas de sueño',
    sleepQualityScore: 'Puntuación de calidad del sueño',
    
    // Mood related
    mood: 'Estado de ánimo',
    moodScore: 'Puntuación del estado de ánimo',
    moodTracking: 'Seguimiento del estado de ánimo',
    
    // Exercise related
    exercise: 'Ejercicio',
    exercises: 'Ejercicios',
    workout: 'Entrenamiento',
    workoutPlan: 'Plan de entrenamiento',
    
    // Nutrition related
    nutrition: 'Nutrición',
    nutritionPlan: 'Plan de nutrición',
    calories: 'Calorías',
    
    // Medical related
    medical: 'Médico',
    medicalRecord: 'Registro médico',
    medication: 'Medicamento',
    
    // Goal related
    goal: 'Objetivo',
    goals: 'Objetivos',
    goalSetting: 'Establecimiento de objetivos',
    goalTracking: 'Seguimiento de objetivos',
    
    // Progress related
    progressTracking: 'Seguimiento del progreso',
    progressReport: 'Informe de progreso',
    
    // AI related
    ai: 'IA',
    aiAssistant: 'Asistente IA',
    aiRecommendation: 'Recomendación IA',
    
    // Notification related
    notification: 'Notificación',
    notifications: 'Notificaciones',
    reminder: 'Recordatorio',
    reminders: 'Recordatorios',
    
    // Privacy related
    privacy: 'Privacidad',
    privacySettings: 'Configuración de privacidad',
    dataProtection: 'Protección de datos',
    
    // Sync related
    sync: 'Sincronización',
    syncing: 'Sincronizando',
    syncComplete: 'Sincronización completa',
    
    // Error messages
    errorOccurred: 'Ocurrió un error',
    tryAgain: 'Intentar de nuevo',
    connectionError: 'Error de conexión',
    
    // Success messages
    successMessage: 'Éxito',
    savedSuccessfully: 'Guardado exitosamente',
    updatedSuccessfully: 'Actualizado exitosamente',
    
    // Additional terms
    viewDetails: 'Ver Detalles',
    viewRecords: 'Ver registros',
    minutes: 'minutos',
    errorText: 'Texto de error',
    userNotFound: 'Usuario no encontrado',
    
    // Settings Screen specific
    resetSettingsConfirm: '¿Estás seguro de que quieres restablecer todas las configuraciones por defecto?',
    clearCacheConfirm: '¿Estás seguro de que quieres limpiar la caché de la aplicación?',
    clear: 'Limpiar',
    reset: 'Restablecer',
    settingsResetSuccess: 'Las configuraciones han sido restablecidas por defecto',
    cacheCleared: 'Caché limpiada exitosamente',
    failedToClearCache: 'Error al limpiar la caché',
    
    // QR Code related
    generateQRCode: 'Generar Código QR',
    qrCodeGenerated: 'Código QR Generado',
    shareQRCode: 'Compartir Código QR',
    scanQRCode: 'Escanear Código QR',
    qrCodeError: 'Error al generar código QR',
    
    // Health Passport specific
    healthPassportTitle: 'Pasaporte de Salud',
    blockchainSecured: 'Asegurado por blockchain',
    universalAccess: 'Acceso Universal',
    hipaaCompliant: 'Cumple con HIPAA',
    personalInformation: 'Información Personal',
    emergencyContact: 'Contacto de Emergencia',
    currentVitalSigns: 'Signos Vitales Actuales',
    currentMedications: 'Medicamentos Actuales',
    medicalRecords: 'Registros Médicos',
    dataSharingAccess: 'Compartir Datos y Acceso',
    recentAccessLog: 'Registro de Acceso Reciente',
    sharingPermissions: 'Permisos de Compartir',
    emergencyServices: 'Servicios de Emergencia',
    fullAccessDuringEmergencies: 'Acceso completo durante emergencias',
    primaryCarePhysician: 'Médico de Atención Primaria',
    fullMedicalHistoryAccess: 'Acceso completo al historial médico',
    specialists: 'Especialistas',
    relevantRecordsOnly: 'Solo registros relevantes',
    managePermissions: 'Gestionar Permisos',
    exportHealthData: 'Exportar Datos de Salud',
    downloadCompleteHealthPassport: 'Descarga tu pasaporte de salud completo para registros personales o compartir con nuevos proveedores.',
    exportPDF: 'Exportar PDF',
    shareSecurely: 'Compartir de Forma Segura',
    bloodType: 'Tipo de Sangre',
    allergies: 'Alergias',
    spouse: 'Cónyuge',
    relationship: 'Relación',
    phone: 'Teléfono',
    updated: 'Actualizado',
    bmi: 'IMC',
    prescribedBy: 'Prescrito por',
    selfAdministered: 'Auto-administrado',
    labResults: 'Resultados de Laboratorio',
    vaccination: 'Vacunación',
    prescription: 'Prescripción',
    routineConsultation: 'Consulta de rutina',
    labResultsUpload: 'Subida de resultados de laboratorio',
    addMedicalRecord: 'Agregar Registro Médico',
    controlWhoCanAccess: 'Controla quién puede acceder a tu información de salud',
    accessor: 'Acceso',
    purpose: 'Propósito',
    dataAccessed: 'Datos Accedidos',
    active: 'activo',
    download: 'Descargar',
    share: 'Compartir',
    overview: 'Resumen',
    records: 'Registros',
    sharing: 'Compartir',
    quickAccessQR: 'Código QR para acceso rápido',
  },
  French: {
    // Settings
    settings: 'Paramètres',
    appSettings: 'Paramètres de l\'App',
    appearance: 'Apparence',
    darkMode: 'Mode Sombre',
    language: 'Langue',
    units: 'Unités',
    audioHaptics: 'Audio et Haptique',
    soundEffects: 'Effets Sonores',
    hapticFeedback: 'Retour Haptique',
    dataSync: 'Données et Synchronisation',
    autoSync: 'Synchronisation Automatique',
    offlineMode: 'Mode Hors Ligne',
    highQualityImages: 'Images Haute Qualité',
    backgroundRefresh: 'Actualisation en Arrière-plan',
    advanced: 'Avancé',
    betaFeatures: 'Fonctionnalités Bêta',
    clearCache: 'Vider le Cache',
    resetSettings: 'Réinitialiser les Paramètres',
    appInformation: 'Informations de l\'App',
    version: 'Version',
    build: 'Build',
    lastUpdated: 'Dernière Mise à Jour',
    
    // Common
    home: 'Accueil',
    profile: 'Profil',
    health: 'Santé',
    fitness: 'Fitness',
    wellness: 'Bien-être',
    aiChat: 'Chat IA',
    back: 'Retour',
    save: 'Sauvegarder',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    add: 'Ajouter',
    view: 'Voir',
    start: 'Commencer',
    complete: 'Terminer',
    next: 'Suivant',
    previous: 'Précédent',
    loading: 'Chargement',
    error: 'Erreur',
    success: 'Succès',
    user: 'Utilisateur',
    
    // Home Screen
    goodMorning: 'Bonjour',
    goodAfternoon: 'Bon après-midi',
    goodEvening: 'Bonsoir',
    todaysOverview: 'Aperçu d\'Aujourd\'hui',
    activityRings: 'Anneaux d\'Activité',
    closeYourRings: 'Fermez vos anneaux aujourd\'hui',
    activeGoals: 'Objectifs Actifs',
    noActiveGoals: 'Aucun objectif actif',
    setFirstGoal: 'Définissez votre premier objectif pour commencer votre parcours de bien-être',
    createGoal: 'Créer un Objectif',
    quickActions: 'Actions Rapides',
    healthCheck: 'Bilan de Santé',
    logVitals: 'Enregistrer les signes vitaux',
    startWorkout: 'Commencer l\'Entraînement',
    getMoving: 'Bougez',
    mindfulness: 'Pleine Conscience',
    findPeace: 'Trouvez la paix',
    aiCoach: 'Coach IA',
    getAdvice: 'Obtenir des conseils',
    upcoming: 'À venir',
    viewCalendar: 'Voir le Calendrier',
    doctorAppointment: 'Rendez-vous Médical',
    workoutSession: 'Séance d\'Entraînement',
    
    // Profile Screen
    yourWellnessJourney: 'Votre parcours de bien-être',
    healthOverview: 'Aperçu de la Santé',
    avgHeartRate: 'Fréquence Cardiaque Moyenne',
    dailySteps: 'Pas Quotidiens',
    moodToday: 'Humeur Aujourd\'hui',
    achievements: 'Réalisations',
    goalsProgress: 'Progrès des Objectifs',
    overallProgress: 'Progrès Global',
    goalsCompleted: 'objectifs terminés',
    noActiveGoalsProfile: 'Aucun objectif actif',
    setFirstGoalProfile: 'Définissez votre premier objectif pour commencer à suivre vos progrès',
    profileSettings: 'Paramètres du Profil',
    editProfile: 'Modifier le Profil',
    updatePersonalInfo: 'Mettre à jour vos informations personnelles',
    healthPassport: 'Passeport Santé',
    viewHealthSummary: 'Voir votre résumé de santé',
    viewWellnessMilestones: 'Voir vos jalons de bien-être',
    appSettingsDesc: 'Notifications, confidentialité et plus',
    recentAchievements: 'Réalisations Récentes',
    viewAll: 'Voir Tout',
    goalAchiever: 'Réalisateur d\'Objectifs',
    completedFirstGoal: 'Vous avez terminé votre premier objectif de bien-être !',
    consistencyMaster: 'Maître de la Cohérence',
    sevenDayStreak: 'Vous avez maintenu une série de 7 jours d\'enregistrements quotidiens',
    
    // Health Screen
    yourWellnessDashboard: 'Votre tableau de bord de bien-être',
    healthStatus: 'État de Santé',
    allSystemsGood: 'Tous les systèmes semblent bons',
    healthScore: 'Score de Santé',
    riskFactors: 'Facteurs de Risque',
    trackedMetrics: 'Métriques Suivies',
    symptomChecker: 'Vérificateur de Symptômes',
    aiAssessment: 'Évaluation IA',
    virtualConsult: 'Consultation Virtuelle',
    talkToDoctor: 'Parler au docteur',
    aiNavigator: 'Navigateur IA',
    healthGuidance: 'Conseils de santé',
    vitalSigns: 'Signes Vitaux',
    addReading: 'Ajouter une Lecture',
    heartRate: 'Fréquence Cardiaque',
    bloodPressure: 'Tension Artérielle',
    weight: 'Poids',
    sleepQuality: 'Qualité du Sommeil',
    upcomingAppointments: 'Rendez-vous à Venir',
    seeAll: 'Voir Tout',
    noUpcomingAppointments: 'Aucun rendez-vous à venir',
    scheduleHealthCheckup: 'Planifiez votre prochain bilan de santé ou consultation',
    scheduleAppointment: 'Planifier un Rendez-vous',
    medications: 'Médicaments',
    manage: 'Gérer',
    noActiveMedications: 'Aucun médicament actif',
    addMedicationsTrack: 'Ajoutez vos médicaments pour suivre les dosages et les horaires',
    addMedication: 'Ajouter un Médicament',
    healthInsights: 'Aperçus Santé',
    greatProgress: 'Excellent Progrès !',
    heartRateHealthy: 'Votre fréquence cardiaque a été constamment dans la plage saine cette semaine. Continuez le bon travail avec vos exercices cardio !',
    sleepOptimization: 'Optimisation du Sommeil',
    trackSleepQuality: 'Considérez suivre votre qualité de sommeil pour mieux comprendre vos modèles d\'énergie et votre santé globale.',
    
    // Fitness Screen
    stayStrongHealthy: 'Restez fort, restez en bonne santé',
    caloriesBurned: 'Calories Brûlées',
    activeMinutes: 'Minutes Actives',
    workouts: 'Entraînements',
    strength: 'Force',
    quickStart: 'Démarrage Rapide',
    aiTrainer: 'Entraîneur IA',
    personalizedWorkouts: 'Entraînements personnalisés',
    calorieScanner: 'Scanner de Calories',
    trackNutrition: 'Suivre la nutrition',
    groupTraining: 'Entraînement de Groupe',
    joinOthers: 'Rejoindre les autres',
    assessment: 'Évaluation',
    testFitness: 'Tester la condition physique',
    todaysWorkouts: 'Entraînements d\'Aujourd\'hui',
    noWorkoutsScheduled: 'Aucun entraînement programmé',
    startFitnessJourney: 'Commencez votre parcours fitness avec un entraînement rapide',
    scheduleWorkout: 'Programmer un Entraînement',
    progressMetrics: 'Métriques de Progrès',
    featuredTrainers: 'Entraîneurs en Vedette',
    noTrainersAvailable: 'Aucun entraîneur disponible',
    connectProfessionalTrainers: 'Connectez-vous avec des entraîneurs professionnels pour atteindre vos objectifs',
    findTrainers: 'Trouver des Entraîneurs',
    insights: 'Aperçus',
    excellentProgress: 'Progrès Excellent !',
    increasedWorkoutIntensity: 'Vous avez augmenté l\'intensité de votre entraînement de 15% cette semaine. Continuez à repousser vos limites !',
    recoveryTime: 'Temps de Récupération',
    considerRestDays: 'Considérez ajouter plus de jours de repos entre les entraînements intenses pour une récupération optimale.',
    viewInsights: 'Voir les Aperçus',
    burnedToday: 'brûlées aujourd\'hui',
    activeTime: 'temps actif',
    bookSession: 'Réserver une Séance',
    
    // Wellness Screen
    mindBodySoul: 'Esprit, corps et âme',
    howAreYouFeeling: 'Comment vous sentez-vous ?',
    feelingGood: 'Je me sens bien',
    tapToLogMood: 'Appuyez pour enregistrer votre humeur',
    energy: 'Énergie',
    activeHabits: 'Habitudes Actives',
    checkIn: 'Enregistrement',
    logMood: 'Enregistrer l\'Humeur',
    trackFeelings: 'Suivre les sentiments',
    nutritionScanner: 'Scanner de Nutrition',
    trackFood: 'Suivre la nourriture',
    sleepTracker: 'Suivi du Sommeil',
    monitorRest: 'Surveiller le repos',
    breathe: 'Respirer',
    relaxMind: 'Détendre l\'esprit',
    wellnessScores: 'Scores de Bien-être',
    energyLevel: 'Niveau d\'Énergie',
    resilience: 'Résilience',
    improving: 'S\'améliore',
    declining: 'Décline',
    stable: 'Stable',
    dailyCheckIn: 'Enregistrement Quotidien',
    readyForCheckIn: 'Prêt pour votre enregistrement quotidien ?',
    reflectOnDay: 'Prenez un moment pour réfléchir à votre journée et suivre votre bien-être',
    checkInComplete: 'Enregistrement Terminé !',
    completedDailyCheckIn: 'Excellent travail en terminant votre enregistrement quotidien de bien-être. Continuez sur votre lancée !',
    todaysHabits: 'Habitudes d\'Aujourd\'hui',
    addHabit: 'Ajouter une Habitude',
    noActiveHabitsWellness: 'Aucune habitude active',
    buildHealthyHabits: 'Construisez des habitudes saines pour améliorer votre bien-être quotidien',
    createFirstHabit: 'Créer Votre Première Habitude',
    dayStreak: 'série de jours',
    moodImprovement: 'Amélioration de l\'Humeur',
    moodConsistentlyPositive: 'Votre humeur a été constamment positive cette semaine. Continuez l\'excellent travail avec votre routine de bien-être !',
    energyBoost: 'Boost d\'Énergie',
    tryMorningMeditation: 'Essayez d\'ajouter une méditation matinale de 10 minutes pour augmenter vos niveaux d\'énergie tout au long de la journée.',
    
    // AI Chat Screen
    aiHealthCoach: 'Coach Santé IA',
    personalWellnessAssistant: 'Votre assistant personnel de bien-être',
    oneHealthAI: 'IA Une Santé',
    onlineReady: 'En ligne et Prêt',
    personalizedInsights: 'Aperçus Personnalisés',
    aiThinking: 'L\'IA réfléchit...',
    askAnythingHealth: 'Demandez-moi n\'importe quoi sur votre santé',
    goalProgress: 'Progrès de l\'Objectif',
    motivation: 'Motivation',
    newPlan: 'Nouveau Plan',
    dailyFocus: 'Focus Quotidien',
    
    // Common Status
    normal: 'normal',
    elevated: 'élevé',
    good: 'bon',
    excellent: 'excellent',
    okay: 'correct',
    low: 'bas',
    terrible: 'terrible',
    
    // Units
    bpm: 'bpm',
    mmHg: 'mmHg',
    kg: 'kg',
    score: 'score',
    kcal: 'kcal',
    min: 'min',
    steps: 'pas',
    earned: 'gagné',
    feeling: 'ressenti',
    
    // Time
    today: 'aujourd\'hui',
    yesterday: 'hier',
    thisWeek: 'cette semaine',
    lastNight: 'hier soir',
    daysAgo: 'il y a des jours',
    weekAgo: 'il y a une semaine',
    
    // Login & Onboarding
    signInWithPhone: 'Se connecter avec le téléphone',
    sendVerificationCode: 'Envoyer le code de vérification',
    enterVerificationCode: 'Entrez le code de vérification',
    verifyAndContinue: 'Vérifier et continuer',
    phoneNumber: 'Numéro de téléphone',
    verificationCode: 'Code de vérification',
    resendCode: 'Renvoyer le code',
    didntReceiveCode: 'Vous n\'avez pas reçu le code ?',
    letsGetToKnowYou: 'Apprenons à vous connaître',
    personalizeHealthJourney: 'Nous utiliserons ceci pour personnaliser votre parcours de santé',
    fullName: 'Nom complet',
    enterYourName: 'Entrez votre nom',
    nationalId: 'Carte d\'identité nationale',
    email: 'E-mail',
    basicInformation: 'Informations de base',
    accurateRecommendations: 'Cela nous aide à fournir des recommandations plus précises',
    age: 'Âge',
    gender: 'Genre',
    male: 'Masculin',
    female: 'Féminin',
    other: 'Autre',
    preferNotToSay: 'Préfère ne pas dire',
    bodyMeasurements: 'Mesures corporelles',
    calculateFitnessNeeds: 'Nous utiliserons ceci pour calculer vos besoins de fitness',
    height: 'Taille',
    enterYourHeight: 'Entrez votre taille',
    enterYourWeight: 'Entrez votre poids',
    uploadMedicalReports: 'Télécharger les rapports médicaux',
    whatAreYourGoals: 'Quels sont vos objectifs ?',
    selectAllThatApply: 'Sélectionnez tout ce qui s\'applique à vous',
    loseWeight: 'Perdre du poids',
    buildMuscle: 'Construire du muscle',
    improveFitness: 'Améliorer la condition physique',
    increaseStrength: 'Augmenter la force',
    improveFlex: 'Améliorer la flexibilité',
    reduceStress: 'Réduire le stress',
    betterSleepOnboarding: 'Meilleur sommeil',
    moreEnergy: 'Plus d\'énergie',
    medicalHistory: 'Antécédents médicaux',
    understandHealthBackground: 'Aidez-nous à comprendre vos antécédents de santé',
    anyConditions: 'Avez-vous l\'une de ces conditions ?',
    fitnessLevel: 'Niveau de condition physique',
    rightWorkoutPlan: 'Cela nous aide à créer le bon plan d\'entraînement',
    beginner: 'Débutant',
    intermediate: 'Intermédiaire',
    advanced: 'Avancé',
    newToExercise: 'Nouveau à l\'exercice ou de retour après une pause',
    exerciseRegularly: 'Je fais de l\'exercice 2-3 fois par semaine régulièrement',
    exerciseConsistently: 'Je fais de l\'exercice 4+ fois par semaine de manière cohérente',
    lifestyleInformation: 'Informations sur le mode de vie',
    dailyHabits: 'Parlez-nous de vos habitudes quotidiennes',
    averageSleepHours: 'Heures de sommeil moyennes par nuit',
    currentStressLevel: 'Niveau de stress actuel (1-10)',
    dietaryPreferences: 'Préférences alimentaires',
    occupation: 'Profession',
    behavioralPreferences: 'Préférences comportementales',
    howMotivated: 'Aidez-nous à comprendre comment vous aimez être motivé',
    whatMotivatesYou: 'Qu\'est-ce qui vous motive le plus ?',
    competitionChallenges: 'Compétition et défis',
    teamCommunity: 'Équipe et communauté',
    personalAchievementMotivation: 'Réalisation personnelle',
    gentleSupport: 'Soutien doux',
    preferredWorkoutTime: 'Heure d\'entraînement préférée',
    morning: 'Matin',
    afternoon: 'Après-midi',
    evening: 'Soir',
    flexible: 'Flexible',
    reminderStyle: 'Style de rappel',
    gentle: 'Doux',
    firm: 'Ferme',
    motivational: 'Motivationnel',
    goalPersonalization: 'Personnalisation des objectifs',
    customizeGoalSetting: 'Personnalisons votre expérience de définition d\'objectifs',
    primaryFocus: 'Quel est votre objectif principal ?',
    balancedFocus: 'Équilibré',
    whatMotivatesYouSelect: 'Qu\'est-ce qui vous motive ? (Sélectionnez tout ce qui s\'applique)',
    healthImprovement: 'Amélioration de la santé',
    weightManagement: 'Gestion du poids',
    stressRelief: 'Soulagement du stress',
    betterSleepGoal: 'Meilleur sommeil',
    increasedEnergy: 'Énergie accrue',
    socialConnection: 'Connexion sociale',
    personalAchievementGoal: 'Réalisation personnelle',
    diseasePrevention: 'Prévention des maladies',
    preferredGoalTimeframe: 'Délai d\'objectif préféré',
    shortTerm: 'Court (1-3 mois)',
    mediumTerm: 'Moyen (3-6 mois)',
    longTerm: 'Long (6+ mois)',
    trackingDetail: 'Combien de détails voulez-vous dans le suivi ?',
    detailed: 'Détaillé',
    simple: 'Simple',
    minimal: 'Minimal',
    specificGoals: 'Objectifs spécifiques',
    personalizedGoalsSetup: 'Configurons vos objectifs personnalisés',
    weightGoal: 'Objectif de poids',
    loseWeightGoal: 'Perdre du poids',
    gainWeight: 'Prendre du poids',
    maintainWeight: 'Maintenir le poids',
    reduceBodyWeight: 'Réduire le poids corporel',
    increaseBodyWeight: 'Augmenter le poids corporel',
    keepCurrentWeight: 'Garder le poids actuel',
    targetWeight: 'Poids cible',
    timeframeMonths: 'Délai (mois)',
    energyGoal: 'Objectif d\'énergie',
    increaseEnergyGoal: 'Augmenter l\'énergie',
    stabilizeEnergy: 'Stabiliser l\'énergie',
    betterMorningEnergy: 'Meilleure énergie matinale',
    feelMoreEnergetic: 'Se sentir plus énergique tout au long de la journée',
    avoidEnergyCrashes: 'Éviter les chutes d\'énergie et maintenir des niveaux stables',
    wakeUpRefreshed: 'Se réveiller en se sentant plus rafraîchi',
    targetEnergyLevel: 'Niveau d\'énergie cible (1-10)',
    stressReductionGoal: 'Objectif de réduction du stress',
    targetStressLevel: 'Niveau de stress cible (1-10, plus bas est mieux)',
    continueBtn: 'Continuer',
    completeSetup: 'Terminer la configuration',
    
    // Additional common terms
    camera: 'Caméra',
    gallery: 'Galerie',
    optional: 'Optionnel',
    sending: 'Envoi',
    verifying: 'Vérification',
    encrypted: 'Chiffré',
    neverShared: 'Jamais partagé',
    thirdParties: 'Tiers',
    phoneEncrypted: 'Votre numéro de téléphone est chiffré et jamais partagé avec des tiers',
    sendingCode: 'Envoi du code...',
    verifyingCode: 'Vérification...',
    sentCodeTo: 'Nous avons envoyé un code à 4 chiffres à',
    
    // Additional UI elements
    distance: 'Distance',
    km: 'km',
    activeTimeShort: 'Temps actif',
    
    // Additional wellness terms
    meditation: 'Méditation',
    morningCalm: 'Calme matinal',
    stressReliefMeditation: 'Soulagement du stress',
    sleepStories: 'Histoires pour dormir',
    
    // Additional fitness terms
    pushUps: 'Pompes',
    squats: 'Squats',
    customWorkout: 'Entraînement personnalisé',
    
    // Additional health terms
    provider: 'Fournisseur',
    appointment: 'Rendez-vous',
    dosage: 'Dosage',
    frequency: 'Fréquence',
    
    // Additional profile terms
    totalGoals: 'Objectifs totaux',
    completedGoals: 'Objectifs terminés',
    progressPercentage: 'Pourcentage de progrès',
    
    // Additional onboarding terms
    chronicConditions: 'Conditions chroniques',
    fitnessLimitations: 'Limitations de fitness',
    ehrSystem: 'Système DSE',
    connectEHR: 'Connecter DSE',
    ehrConnected: 'DSE connecté',
    primaryCareProvider: 'Fournisseur de soins primaires',
    lastPhysicalExam: 'Dernier examen physique',
    
    // Status messages
    planCreated: 'Plan créé !',
    personalizedPlanCreated: 'Votre plan personnalisé a été créé et ajouté à votre profil. Vous pouvez suivre vos progrès dans la section Santé.',
    failedToCreatePlan: 'Échec de la création du plan. Veuillez réessayer.',
    
    // Additional common terms
    of: 'de',
    at: 'à',
    on: 'sur',
    and: 'et',
    or: 'ou',
    with: 'avec',
    without: 'sans',
    for: 'pour',
    from: 'de',
    to: 'à',
    in: 'dans',
    
    // Sleep related
    sleep: 'Sommeil',
    sleepHours: 'Heures de sommeil',
    sleepQualityScore: 'Score de qualité du sommeil',
    
    // Mood related
    mood: 'Humeur',
    moodScore: 'Score d\'humeur',
    moodTracking: 'Suivi de l\'humeur',
    
    // Exercise related
    exercise: 'Exercice',
    exercises: 'Exercices',
    workout: 'Entraînement',
    workoutPlan: 'Plan d\'entraînement',
    
    // Nutrition related
    nutrition: 'Nutrition',
    nutritionPlan: 'Plan de nutrition',
    calories: 'Calories',
    
    // Medical related
    medical: 'Médical',
    medicalRecord: 'Dossier médical',
    medication: 'Médicament',
    
    // Goal related
    goal: 'Objectif',
    goals: 'Objectifs',
    goalSetting: 'Définition d\'objectifs',
    goalTracking: 'Suivi des objectifs',
    
    // Progress related
    progressTracking: 'Suivi des progrès',
    progressReport: 'Rapport de progrès',
    
    // AI related
    ai: 'IA',
    aiAssistant: 'Assistant IA',
    aiRecommendation: 'Recommandation IA',
    
    // Notification related
    notification: 'Notification',
    notifications: 'Notifications',
    reminder: 'Rappel',
    reminders: 'Rappels',
    
    // Privacy related
    privacy: 'Confidentialité',
    privacySettings: 'Paramètres de confidentialité',
    dataProtection: 'Protection des données',
    
    // Sync related
    sync: 'Synchronisation',
    syncing: 'Synchronisation en cours',
    syncComplete: 'Synchronisation terminée',
    
    // Error messages
    errorOccurred: 'Une erreur s\'est produite',
    tryAgain: 'Réessayer',
    connectionError: 'Erreur de connexion',
    
    // Success messages
    successMessage: 'Succès',
    savedSuccessfully: 'Sauvegardé avec succès',
    updatedSuccessfully: 'Mis à jour avec succès',
    
    // Additional terms
    viewDetails: 'Voir les Détails',
    viewRecords: 'Voir les dossiers',
    minutes: 'minutes',
    errorText: 'Texte d\'erreur',
    userNotFound: 'Utilisateur non trouvé',
    
    // Settings Screen specific
    resetSettingsConfirm: 'Êtes-vous sûr de vouloir réinitialiser tous les paramètres par défaut ?',
    clearCacheConfirm: 'Êtes-vous sûr de vouloir vider le cache de l\'application ?',
    clear: 'Vider',
    reset: 'Réinitialiser',
    settingsResetSuccess: 'Les paramètres ont été réinitialisés par défaut',
    cacheCleared: 'Cache vidé avec succès',
    failedToClearCache: 'Échec de la vidange du cache',
    
    // QR Code related
    generateQRCode: 'Générer un Code QR',
    qrCodeGenerated: 'Code QR Généré',
    shareQRCode: 'Partager le Code QR',
    scanQRCode: 'Scanner le Code QR',
    qrCodeError: 'Erreur lors de la génération du code QR',
    
    // Health Passport specific
    healthPassportTitle: 'Passeport Santé',
    blockchainSecured: 'Sécurisé par blockchain',
    universalAccess: 'Accès Universel',
    hipaaCompliant: 'Conforme HIPAA',
    personalInformation: 'Informations Personnelles',
    emergencyContact: 'Contact d\'Urgence',
    currentVitalSigns: 'Signes Vitaux Actuels',
    currentMedications: 'Médicaments Actuels',
    medicalRecords: 'Dossiers Médicaux',
    dataSharingAccess: 'Partage de Données et Accès',
    recentAccessLog: 'Journal d\'Accès Récent',
    sharingPermissions: 'Autorisations de Partage',
    emergencyServices: 'Services d\'Urgence',
    fullAccessDuringEmergencies: 'Accès complet pendant les urgences',
    primaryCarePhysician: 'Médecin de Soins Primaires',
    fullMedicalHistoryAccess: 'Accès complet à l\'historique médical',
    specialists: 'Spécialistes',
    relevantRecordsOnly: 'Dossiers pertinents uniquement',
    managePermissions: 'Gérer les Autorisations',
    exportHealthData: 'Exporter les Données de Santé',
    downloadCompleteHealthPassport: 'Téléchargez votre passeport santé complet pour les dossiers personnels ou le partage avec de nouveaux fournisseurs.',
    exportPDF: 'Exporter PDF',
    shareSecurely: 'Partager en Sécurité',
    bloodType: 'Groupe Sanguin',
    allergies: 'Allergies',
    spouse: 'Conjoint(e)',
    relationship: 'Relation',
    phone: 'Téléphone',
    updated: 'Mis à jour',
    bmi: 'IMC',
    prescribedBy: 'Prescrit par',
    selfAdministered: 'Auto-administré',
    labResults: 'Résultats de Laboratoire',
    vaccination: 'Vaccination',
    prescription: 'Prescription',
    routineConsultation: 'Consultation de routine',
    labResultsUpload: 'Téléchargement des résultats de laboratoire',
    addMedicalRecord: 'Ajouter un Dossier Médical',
    controlWhoCanAccess: 'Contrôlez qui peut accéder à vos informations de santé',
    accessor: 'Accès',
    purpose: 'Objectif',
    dataAccessed: 'Données Accédées',
    active: 'actif',
    download: 'Télécharger',
    share: 'Partager',
    overview: 'Aperçu',
    records: 'Dossiers',
    sharing: 'Partage',
    quickAccessQR: 'Code QR pour accès rapide',
  },
};

export const getTranslation = (language: string, key: string): string => {
  const lang = language as keyof typeof translations;
  const langTranslations = translations[lang] || translations.Arabic; // Default to Arabic
  return langTranslations[key as keyof typeof langTranslations] || key;
};

// Helper function to get RTL languages
export const isRTL = (language: string): boolean => {
  const rtlLanguages = ['Arabic'];
  return rtlLanguages.includes(language);
};